import {ITask} from "./types";
import {E_TASK_TYPE} from "./enums";
import {getDefaultId} from "./utils";

export const MOCK_TASKS: ITask[] = [
    {
        type: E_TASK_TYPE.FOOD,
        name: "Bread",
        comment: "Don't eat it for dinner",
        description: "White Ukrainian bread",
        isFavorite: true,
        isFail: false,
        id: getDefaultId(),
        count: 1,
        price: 10,
        cost: 10,
        startDate: 0,
        endDate: 0,
    },
    {
        type: E_TASK_TYPE.FOOD,
        name: "Apple",
        comment: "Very useful",
        description: "Red apple",
        isFavorite: true,
        isFail: false,
        id: getDefaultId(),
        count: 1,
        price: 15,
        cost: 15,
        startDate: 0,
        endDate: 0,
    },
    {
        type: E_TASK_TYPE.FOOD,
        name: "Cupcake",
        comment: "Very sweet",
        description: "Cupcake with chocolate",
        isFavorite: false,
        isFail: false,
        id: getDefaultId(),
        count: 1,
        price: 40,
        cost: 40,
        startDate: 0,
        endDate: 0,
    },
    {
        type: E_TASK_TYPE.GOODS,
        name: "Knife",
        comment: "Dangerous",
        description: "Iron knife",
        isFavorite: false,
        isFail: false,
        id: getDefaultId(),
        count: 1,
        price: 100,
        cost: 100,
        startDate: 0,
        endDate: 0,
    },
    {
        type: E_TASK_TYPE.GOODS,
        name: "Table",
        comment: "New desktop",
        description: "Brown table",
        isFavorite: false,
        isFail: false,
        id: getDefaultId(),
        count: 1,
        price: 1000,
        cost: 1000,
        startDate: 0,
        endDate: 0,
    }
];
