export enum CLASSIFICATION {
    MODIFIER = "modifier",
    TYPE_ASSERTION = "type_assertion",
    CONTROL_FLOW = "control_flow",
    PRIMITIVE_TYPE = "primitive_type",
    STRUCTURE = "structure",
    DECLARATION = "declaration",
    MISCELLANEOUS = "miscellaneous",
    OPERATOR = "operator",
    INTERFACE = "interface",
    MODULE = "module",
    INHERITANCE = "inheritance",
    BOOLEAN_VALUE = "boolean_value",
    INSTANTIATION = "instantiation",
    NULL_TYPE = "null_type",
    ACCESSOR = "accessor",
    CONTEXT = "context",
    GENERATION = "generation",
    TYPE_UTIL = 'type_util',
    DELIMITER = 'delimiter',
    SPECIAL_CHARACTER = 'special_character',
}
