export enum MAIN_ROUTES {
    HOME = "HOME",
    ABOUT = "ABOUT",
    CONTACT = "CONTACT",
}

export enum CARS_ROUTES {
    OLD_CARS = "OLD_CARS",
    NEW_CARS = "NEW_CARS",
    POPULAR_CARS = "POPULAR_CARS",
}

export enum POPULAR_CARS_ROUTES {
    POPULAR_CARS_LIST = "POPULAR_CARS_LIST",
    POPULAR_CARS_DETAILS = "POPULAR_CARS_DETAILS",
}
